// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cldmfhhtmquorozaujev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsZG1maGh0bXF1b3JvemF1amV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTMyNTQsImV4cCI6MjA3MTYyOTI1NH0.EzouqxLvK5ehHpiF66tqa5oFSwla7ojxRlI_7rTphIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});